### ISSUE TITLE
User interface not reachable

### ISSUE THREAD

**Issue by vergissberlin** [GerLech/WebConfig#1]
Hi @GerLech !

this project is still in progress, right?
I really like your way how you set up the form.
Unfortunately, I wasn't able to see the form.
There was no captive portal page or so like in other libraries of this type.

kind regards
André

**Comment by GerLech** [comment]
Hi vergissberlin
Have you tried the example sketch?  This should work for ESP8266 and ESP32.  You need to have SPIFFS space reserved.  To see the Form you need to start a webserver and you have to create the on request callback function in your sketch. In this function you can call the handleFormRequest function from WebConfig instance. This function publish the form top the web server passed as the first parameter.
I hope this helps.

**Comment by vergissberlin** [comment]
I see! I tried the _demo8266_ with my wemos d1 mini. My expectation was to have a webserver included in the demo. Thank you!
