### ISSUE TITLE
Any way to extend MAXVALUES?

### ISSUE THREAD

**Issue by sbormann** [GerLech/WebConfig#10]
Hi, 
many thanks for your great work!
I have a question: Is there any chance to extend MAXVALUES? 
I need 26 values, but if i change MAXVALUES to a value greater than 20, i get JSON: NoMemory...

Again, many thanks and best regards!

**Comment by infrafast** [comment]
Try https://arduinojson.org/v5/assistant/ (or v6) and change the allocated mem size of the jsondocument in the library accordingly

Envoyé de mon iPhone

Le 25 févr. 2021 à 22:33, Sebastian Bormann <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi,
many thanks for your great work!
I have a question: Is there any chance to extend MAXVALUES?
I need 26 values, but if i change MAXVALUES to a value greater than 20, i get JSON: NoMemory...

Again, many thanks and best regards!
