### ISSUE TITLE
Is it possible to add a textfield with multiline (textarea) ?

### ISSUE THREAD

**Issue by macfletzi** [GerLech/WebConfig#11]
Hello,
I like this great work that simplifies configuration so much.

In my application I use a small textfile stored in the internal FS. 
This file contains some variable configuraion data with approx. 30 lines, max. size is 1kByte

I read / write this text file via MQTT, but it would be a great extension, 
if this text file could be accessed via the WebConfig.

I cannot use the text input of the WebConfig, because I need multiline text.

Is it possible to add such a feature?
I tried to modify the code of WebConfig, but I noticed that my programming and html knowledge 
is not sufficient to extend the existing code.
Could you help me?

**Comment by GerLech** [comment]
I added a new input type INPUTTEXTAREA. It does what you want. See release 1.4
