### ISSUE TITLE
Unable to add entry

### ISSUE THREAD

**Issue by ant7511** [GerLech/WebConfig#19]
This library seems awesome, but sadly i cant add more entries.
 `"{"
  "'name':'mqttaddr',"
  "'label':'MQTT Address',"
  "'type':"+String(INPUTTEXT)+","
  "'default':'NN'"
  "},"`

If i add it, it runs only in AP mode, and the only thing which can be seen and modifiable is the device name. 

What i have to do to make it work ??

**Comment by GerLech** [comment]
What I see is the JSON for the first entry. What follows? I would need all the lines beginning with 

> String params = "["

 until

>  "]";

to help

**Comment by ant7511** [comment]
> "{"
  "'name':'MQTTName',"
  "'label':'MQTT Name',"
  "'type':"+String(INPUTTEXT)+","
  "'default':'mqttusername'"
  "},"

i added this into the example, somewhere after the wifi password.  
Finally its become solved, because i only needed login datas and number input  only, so i deleted all unnecessary example entries (included the unknown one which caused the problem) and it works well, so it works well..

**Comment by ant7511** [comment]
i forgot to say, thanks for the lib, it helped me a lot to create a new standalone universal learnable gate opener within 2 hours :)
