### ISSUE TITLE
setXXXX() function

### ISSUE THREAD

**Issue by infrafast** [GerLech/WebConfig#4]
Hello, I am using the library, very good job! 
we have access to the values of a parameter so we could presumably change it via

values[conf.getindex("mytrack")]=xxx

however I think it would make sense to implement the code into a setValue(paramName) and also:
- setLabel(paramName,label) 
- setOption(paramName,index,label,value)

I am planning to do that anyway so I can either submit a pullrequest or fork but maybe you planned to do that anyway ?
Thanks
Thomas

bool WebConfig::setParamOption(const char * paramName,int j,const char * optionL, const char * optionV){
	return setParamOption(getIndex(paramName),j,optionL,optionV);
}

bool WebConfig::setParamOption(int i,int j,const char * optionL, const char * optionV){
	if (j<MAXOPTIONS && i<_count;){
		_description[i].options[j] = optionV;
        	_description[i].labels[j] = optionL;
		return true;
	}else return false;
}

**Comment by GerLech** [comment]
I added the suggested functions and some more. I released the new version 1.2 today

**Comment by infrafast** [comment]
great thanks!

________________________________
De : Gerald Lechner <notifications@github.com>
Envoyé : mercredi 5 février 2020 14:11
À : GerLech/WebConfig <WebConfig@noreply.github.com>
Cc : infrafast <info@infrafast.com>; Author <author@noreply.github.com>
Objet : Re: [GerLech/WebConfig] setXXXX() function (#4)


I added the suggested functions and some more. I released the new version 1.2 today

**Comment by infrafast** [comment]
thanks a lot
