### ISSUE TITLE
Excellent work!

### ISSUE THREAD

**Issue by mitchsf** [GerLech/WebConfig#5]
Are you still supporting this library? I'd like to use it, and there hasn't been any response to previous reports.

Unfortunately because the struct DESCRIPTION allocates memory for the maximum number of options, to each value, more than around 40 values with 15 options, will crash the ESP32 due to memory issues.

I need 70 values with up to 30 options, but most of the 70 only have two or three options. It would be best to create a separate struct for options linked to description, possibly by value and order.

Hopefully you will have time to look into this issue. Thanks again for the excellent work.

**Comment by GerLech** [comment]
I created this library to setup IOT modules with sensor. I never tought off so many values and options. Your problem is not easy to solve. The solution would be to create a class for a single option and at a new instance for an option at runtime as required.

**Comment by mitchsf** [comment]
Thanks for the reply. That's just a little beyond what I can do, but thanks for the great work.
