### ISSUE TITLE
Is a simple way to create multicheckbox?

### ISSUE THREAD

**Issue by sirpete83** [GerLech/WebConfig#8]
Hello,
I have found this great library and would like to use it in one of my projects. I've defined the elements I need. Then I noticed that it would be nice to have a multiple checkbox. The background is as follows: I would like to be able to select individual days of the week. One checkbox each Monday to Sunday, which in the best case scenario are then in one line. The result could be a bit mask, or individual Boolean values that can then be evaluated. Of course, you can now create individual checkboxes, but these are then arranged below one another. Perhaps one could generally provide a further interlacing of elements that summarize the elements that are in one line of the website, if the size of the screen allows it.
Thanks for the great work.

**Comment by GerLech** [comment]
There is no simple way to get what you want, but I like your idea of a multi checkbox in one line. I think I will add such an element which allows up to 16 checkboxes with individual small labels in a line. The entered value will be returned in a 16 bit unsigned integer. It should be in my next release. 
btw The Version 1.3.1 had a typo and did not compile! Version 1.3.2 has fixed this bug.

**Comment by sirpete83** [comment]
Hey,
yes i corrected the typo before I used the lib. Thank you for putting my suggestion into practice. I'm looking forward to testing it out soon.

**Comment by GerLech** [comment]
The multi checkbox is available with release 1.4 from today
