### ISSUE TITLE
New ESP32 Module

### ISSUE THREAD

**Issue by stmb-100** [GerLech/WebConfig#9]
695 / 5000
Hello GerLech
If I use a new ESP module, I cannot write to the SPIFFS because the filesystem does not yet exist. Could you please add a formatting function in case the SPIFFS does not yet exist.

Regards
Stefan

Deutsch:
Wenn ich ein neues ESP Module verwende, kann ich nicht auf das SPIFFS schreiben, da das Filessystem noch nicht existiert. Könnten Sie bitte eine Formatierungsfunktion einbauen für den Fall dass, das SPIFFS noch nicht existiert. 
Gruß
Stefan

about as:
 boolean InitalizeFileSystem() {
 bool initok = false;
 
 initok = SPIFFS.begin();
 
  if (!(initok)) // Format SPIFS, of not formatted. - Try 1
  {
    Serial.println("SPIFFS Dateisystem formatiert.");
    SPIFFS.format();
    initok = SPIFFS.begin();
  }
  if (!(initok)) // Format SPIFS. - Try 2
  {
    SPIFFS.format();
    initok = SPIFFS.begin();
  }
  if (initok) { Serial.println("SPIFFS ist  OK"); } else { Serial.println("SPIFFS ist nicht OK"); }
  return initok;
})

**Comment by GerLech** [comment]
This is fixed with release 1.4
